name: deploy to github pages

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@13.0
        with:
          cli: 1.12.0.1479
      - name: Build html
        run: clojure -X:build
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: build-output
  deploy:
    needs: build
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@v2
        id: deployment